[tool.poetry]
name = "pass_gen"
version = "0.1.0"
description = ""
authors = ["Stark <udbhavsomani18@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
django = "^3.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
